name: "Testing"

on:
  push:
    branches: ["main", "dev"]
    paths:
     - 'bilibili_api/**'
     - 'tests/**'
  
  schedule:
    - cron: '0 4 * * 6'

jobs:
  test-3_8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start test
        env:
          BILI_SESSDATA: ${{ secrets.BILI_SESSDATA }}
          BILI_CSRF: ${{ secrets.BILI_CSRF }}
          BILI_RATELIMIT: 1.5 # WTF? 1 秒间隔每次 action 测试必须有两个函数 timeout
          BILI_BUVID3: ${{ secrets.BILI_BUVID3 }}
          BILI_PHONE: ${{ secrets.BILI_PHONE }}
          BILI_PASSWORD: ${{ secrets.BILI_PASSWORD }}
          BILI_DEDEUSERID: ${{ secrets.BILI_DEDEUSERID }}
        run: "python -m tests.main -a"
